version: "3.8"

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
